openapi: "3.0.3"
# 必須項目
info:
  title: "Shop Review API"
  version: "1.0.0"
# API定義のパス
# pathは複数形で書く
paths:
  "/shops/{shopId}/reviews":
    post:
      summary: "Create review"
      parameters:
        - name: shopId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: "Contens of review"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                score:
                  type: integer
                comment:
                  type: string
      responses:
        "201":
          description: "Success operation"
          headers:
            location:
              description: "New URL of created review"
              schema: { type: string, format: url }

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: { type: string }
                  type: { type: string }
                  message: { type: string }
                  errors:
                    type: array
                    properties:
                      field: { type: string }
                      code: { type: string }